data.raw["quality"]["normal"].localised_name = "Mk1"
data.raw["quality"]["uncommon"].localised_name = "Mk2"
data.raw["quality"]["rare"].localised_name = "Mk3"
data.raw["quality"]["epic"].localised_name = "Mk4"
data.raw["quality"]["legendary"].localised_name = "Mk5"
